Added species planet data models
CSC-415/csc-415-group-the-force pull request #7
Opened 2023-04-13 23:05 UTC by coffmancorrim

Added the code for the planet and species data models to fit the new data model schema

2023-04-13 23:12 UTC, sjsutton27 approved these changes

2023-04-13 23:26 UTC, arthurwb approved these changes

2023-04-14 02:35 UTC, muzzarellimj requested changes
Sorry for so many comments - wanted to make sure I addressed as much as I could while I had time! I think you had an old version of my branch because it didn't include some of the most recent code changes. I'll create a new PR so I can merge my branch into main and then you'll be able to merge main into your branch to have the most recent changes as well. Let me know if you have any questions!

2023-04-14 02:35 UTC, muzzarellimj commented on app/src/main/kotlin/com/example/jocasta/data/SwapiClient.kt
Functions fetchPlanets and fetchSpecies are correct to fetch a PlanetSet, but they'll need matching functions fetchPlanet and fetchSpecies to fetch one of each. Feel free to take a look at the most up-to-date [SwapiClient](https://github.com/CSC-415/csc-415-group-the-force/blob/feature/muzzarelli/app/src/main/kotlin/com/example/jocasta/data/SwapiClient.kt) in the `feature/muzzarelli` branch.

2023-04-14 02:35 UTC, muzzarellimj commented on app/src/main/kotlin/com/example/jocasta/data/model/Planet.kt
> +    @SerializedName("count")
**Note: this comment applies to all data models.** 

@SerializedName should be called as @field:SerializedName to be called within the field scope. Liam mentioned this was to limit scope of annotations to ease runtime compilation.

Additionally, if argument `name` in @field:SerializedName matches the name of the attribute from the API, we don't need the annotation. For example, since the API response already sets this value by the same name (e.g., API response calls it `count` the same way our data model calls it `count`) we can skip the annotation. Feel free to compare the [SWAPI response for /films](https://swapi.dev/api/films) to my [FilmSet data model](https://github.com/CSC-415/csc-415-group-the-force/blob/feature/muzzarelli/app/src/main/kotlin/com/example/jocasta/data/model/Film.kt#L68).

2023-04-14 02:35 UTC, muzzarellimj commented on app/src/main/kotlin/com/example/jocasta/data/model/Planet.kt
> +    @SerializedName("results")
To build upon the above comment, this is the perfect time to use the @field:SerializedName annotation since the API calls this attribute `results` and we call it `planets`. My only recommendation here is change the annotation scope with `field:` as discussed above.

2023-04-14 02:35 UTC, muzzarellimj commented on app/src/main/kotlin/com/example/jocasta/data/model/Planet.kt
> +    val id: Int,
This bit won't parse correctly - since the API doesn't actually report an ID for each resource, we have to take it from the source URL, as seen [here](https://github.com/CSC-415/csc-415-group-the-force/blob/feature/muzzarelli/app/src/main/kotlin/com/example/jocasta/data/model/Film.kt#L25) in the Film data model. To accomplish this, we annotate with @field:SerializedName("url") and @JsonAdapter(DeserializeInt::class), which means we should take the field `url` from the API response, deserialize it with class DeserializeInt to extract the implicit ID from the URL, and set our data model's attribute `id` equal to whatever that number is.

2023-04-14 02:35 UTC, muzzarellimj commented on app/src/main/kotlin/com/example/jocasta/data/model/Planet.kt
> +    val films: List<Int>,
Final example here - @SerializedName can be skipped here since this attribute is called `films` in both the API response and our data model, but we do still need @field:JsonAdapter(DeserializeIntList::class) here to deserialize the array of URL's as a list of integer ID's.

2023-04-14 02:35 UTC, muzzarellimj commented on app/src/main/kotlin/com/example/jocasta/data/repository/SwapiRepository.kt
Same thing as SwapiClient for this class - we'll just need to add fetchPlanet and fetchSpecies accordingly once they're created in SwapiClient.

2023-04-14 02:35 UTC, muzzarellimj commented on app/src/main/kotlin/com/example/jocasta/data/model/Species.kt
Just follow the same guidelines here as Planet.kt!

2023-04-14 02:35 UTC, muzzarellimj commented on app/src/main/kotlin/com/example/jocasta/data/repository/SwapiRepositoryImpl.kt
> +            )
Since `response.body()` should contain a JSON object that'll be deserialized as a PlanetSet and we've already null-checked it at this point, we can just call `ResourceSetResponse.Success(body)` so we don't have to manually set these data class values. This is handy for creating individual data classes (e.g., Planet rather than PlanetSet) where there are 10-15 attributes.

2023-04-14 02:35 UTC, muzzarellimj commented on app/src/main/kotlin/com/example/jocasta/data/repository/SwapiRepositoryImpl.kt
Since two functions will be added to SwapiRepository, this implementation will need those functions created as well. I created the [fetchFilm](https://github.com/CSC-415/csc-415-group-the-force/blob/feature/muzzarelli/app/src/main/kotlin/com/example/jocasta/data/repository/SwapiRepositoryImpl.kt#L30) and [fetchPerson](https://github.com/CSC-415/csc-415-group-the-force/blob/feature/muzzarelli/app/src/main/kotlin/com/example/jocasta/data/repository/SwapiRepositoryImpl.kt#L66) functions for reference.

2023-04-14 02:35 UTC, muzzarellimj commented on app/src/main/kotlin/com/example/jocasta/ui/HomeViewModel.kt
HomeViewModel looks great, and once the fetchPlanet and fetchSpecies functions are created in SwapiClient, SwapiRepository, and SwapiRepositoryImpl, these two functions should be created in DetailViewModel as well. I created [fetchFilm](https://github.com/CSC-415/csc-415-group-the-force/blob/feature/muzzarelli/app/src/main/kotlin/com/example/jocasta/ui/DetailViewModel.kt#L41) in DetailViewModel in the `feature/muzzarelli` branch for reference.

2023-04-18 20:06 UTC, muzzarellimj approved these changes

2023-04-18 20:06 UTC, merged